spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=spycon
spring.datasource.password=myPassword
spring.jpa.open-in-view=false
spring.graphql.graphiql.enabled=true
logging.level.com.smartshop=DEBUG

# Show SQL (development only)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Swagger UI Customization
springdoc.swagger-ui.custom-css=/swagger-custom.css
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.default-models-expand-depth=3
springdoc.swagger-ui.display-operation-id=false
springdoc.swagger-ui.filter=true