spring.application.name=SmartShop
spring.profiles.active=dev

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers,env,prometheus
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.info.env.enabled=true

# Swagger UI Customization
springdoc.swagger-ui.custom-css=/swagger-custom.css
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.default-models-expand-depth=3
springdoc.swagger-ui.display-operation-id=false
springdoc.swagger-ui.filter=true

# Async executor configuration
app.async.core-pool-size=8
app.async.max-pool-size=16
app.async.queue-capacity=200
app.async.keep-alive-seconds=60

